# Generated by Django 4.0.3 on 2022-03-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(choices=[('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('A', 'A'), ('B', 'B')], max_length=30),
        ),
    ]
