# Generated by Django 4.0.3 on 2022-03-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0002_alter_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fret_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='note',
            name='string_number',
            field=models.PositiveIntegerField(),
        ),
    ]
