# Generated by Django 4.0.4 on 2022-06-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0002_author_melody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chord',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visible_guitar.instrument'),
        ),
        migrations.AlterField(
            model_name='chord',
            name='notes',
            field=models.ManyToManyField(to='visible_guitar.note'),
        ),
        migrations.AlterField(
            model_name='melody',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visible_guitar.author'),
        ),
        migrations.AlterField(
            model_name='melody',
            name='chords',
            field=models.ManyToManyField(to='visible_guitar.chord'),
        ),
    ]
