# Generated by Django 4.0.5 on 2022-06-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0004_alter_author_name_alter_chord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melody',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='visible_guitar.author'),
        ),
    ]
