# Generated by Django 4.0.3 on 2022-03-22 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0004_alter_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='string_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
