# Generated by Django 4.0.4 on 2022-06-10 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicianuser',
            options={'verbose_name': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='musicianuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='musicianuser',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
