# Generated by Django 4.0.4 on 2022-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0003_alter_chord_instrument_alter_chord_notes_and_more'),
        ('users', '0002_alter_musicianuser_options_alter_musicianuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianuser',
            name='chords',
            field=models.ManyToManyField(to='visible_guitar.chord'),
        ),
        migrations.AddField(
            model_name='musicianuser',
            name='melodies',
            field=models.ManyToManyField(to='visible_guitar.melody'),
        ),
    ]
