# Generated by Django 4.0.5 on 2022-06-10 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_musicianuser_chords_musicianuser_melodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianuser',
            name='email',
            field=models.EmailField(max_length=128, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='musicianuser',
            name='username',
            field=models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
