# Generated by Django 4.0.5 on 2022-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visible_guitar', '0005_alter_melody_author'),
        ('users', '0004_alter_musicianuser_email_alter_musicianuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicianuser',
            name='chords',
            field=models.ManyToManyField(blank=True, to='visible_guitar.chord'),
        ),
        migrations.AlterField(
            model_name='musicianuser',
            name='melodies',
            field=models.ManyToManyField(blank=True, to='visible_guitar.melody'),
        ),
    ]
